=== pavelhan/javaLearning/XML/src/xsd.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="xx" xmlns:tns="xx">
    <element name="plans">
        <complexType>
            <sequence>
                <element name="plan" type="tns:plan" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>
    <complexType name="plan">
        <sequence>
            <element name="name"/>
            <element name="operator"/>
            <element name="Payroll">
                <simpleType>
                    <restriction base="integer">
                        <minInclusive value="0"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="CallPrices" type="tns:Callprices">
            </element>
            <element name="SMSprice">
                <simpleType>
                    <restriction base="integer">
                        <minInclusive value="0"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="Parameters" type="tns:Parameters"/>
        </sequence>
    </complexType>
    <complexType name="Callprices">
        <sequence>
            <element name="internalCalls">
                <simpleType>
                    <restriction base="integer">
                        <minInclusive value="0"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="outboundCalls">
                <simpleType>
                    <restriction base="integer">
                        <minInclusive value="0"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="regularPhones">
                <simpleType>
                    <restriction base="integer">
                        <minInclusive value="0"/>
                    </restriction>
                </simpleType>
            </element>
        </sequence>
    </complexType>
    <complexType name="Parameters">
        <sequence>
            <element name="favoriteNumbers">
                <simpleType>
                    <restriction base="integer">
                        <minInclusive value="0"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="tarrification">
                <simpleType>
                    <restriction base="integer">
                        <enumeration value="12"/>
                        <enumeration value="60"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="priceForPlanActivation">
                <simpleType>
                    <restriction base="integer">
                        <minInclusive value="0"/>
                    </restriction>
                </simpleType>
            </element>
        </sequence>
    </complexType>
</schema>

=== pavelhan/javaLearning/XML/src/mobile.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:plans xmlns:tns="xx" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="xx xsd.xsd">
    <plan>
        <name>Lifestyle</name>
        <operator>Vodaphone</operator>
        <Payroll>85</Payroll>
        <CallPrices>
            <internalCalls>0</internalCalls>
            <outboundCalls>2</outboundCalls>
            <regularPhones>3</regularPhones>
        </CallPrices>
        <SMSprice>0</SMSprice>
        <Parameters>
            <favoriteNumbers>5</favoriteNumbers>
            <tarrification>12</tarrification>
            <priceForPlanActivation>10</priceForPlanActivation>
        </Parameters>
    </plan>
    <plan>
        <name>Nice</name>
        <operator>Life</operator>
        <Payroll>100</Payroll>
        <CallPrices>
            <internalCalls>1</internalCalls>
            <outboundCalls>3</outboundCalls>
            <regularPhones>5</regularPhones>
        </CallPrices>
        <SMSprice>5</SMSprice>
        <Parameters>
            <favoriteNumbers>3</favoriteNumbers>
            <tarrification>12</tarrification>
            <priceForPlanActivation>5</priceForPlanActivation>
        </Parameters>
    </plan>
    <plan>
        <name>Fresh</name>
        <operator>Kyivstar</operator>
        <Payroll>50</Payroll>
        <CallPrices>
            <internalCalls>0</internalCalls>
            <outboundCalls>5</outboundCalls>
            <regularPhones>1</regularPhones>
        </CallPrices>
        <SMSprice>0</SMSprice>
        <Parameters>
            <favoriteNumbers>1</favoriteNumbers>
            <tarrification>60</tarrification>
            <priceForPlanActivation>40</priceForPlanActivation>
        </Parameters>
    </plan>
</tns:plans>
